#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := google-iot

EXTRA_COMPONENT_DIRS := $(realpath ../esp-google-iot)

include $(IDF_PATH)/make/project.mk
